# Generated by Django 6.0.4 on 2026-04-21 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_limite_devolucion', models.PositiveIntegerField(default=2, help_text='Horas máximas para devolver un medicamento antes de considerarse aplicado.')),
            ],
            options={
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('principio_activo', models.CharField(max_length=200)),
                ('forma_farmaceutica', models.CharField(max_length=100)),
                ('registro_invima', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_bodega_principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mov', models.CharField(choices=[('ENTRADA', 'Ingreso por Compra'), ('SALIDA', 'Salida a Paciente'), ('TRASLADO', 'Traslado entre Bodegas'), ('DEVOLUCION', 'Devolución de Paciente')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_paciente', models.CharField(blank=True, max_length=50, null=True)),
                ('documento_referencia', models.ForeignKey(blank=True, help_text='Para devoluciones, apunta a la salida original', null=True, on_delete=django.db.models.deletion.PROTECT, to='kardex.documento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='kardex.ubicacion')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='kardex.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('cantidad', models.PositiveIntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='kardex.documento')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kardex.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador Central'), ('REGENTE', 'Regente de Farmacia (Bodega)'), ('ENFERMERA', 'Enfermería (Carro de Paro)')], max_length=20)),
                ('numero_identificacion', models.CharField(max_length=50, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('ubicacion_asignada', models.ForeignKey(blank=True, help_text='Ubicación física donde este usuario tiene permisos.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kardex.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='InventarioStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=10)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.medicamento')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kardex.ubicacion')),
            ],
            options={
                'unique_together': {('ubicacion', 'medicamento', 'lote')},
            },
        ),
    ]
