# Generated by Django 6.0.4 on 2026-04-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='concentracion',
            field=models.CharField(blank=True, help_text='Ej: 500mg, 0.3%, 1g', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='presentacion',
            field=models.CharField(blank=True, help_text='Ej: Caja x 30, Frasco x 100ml', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código ATC, CUM o interno', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='forma_farmaceutica',
            field=models.CharField(help_text='Ej: Tableta, Solución, Jarabe', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='principio_activo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='registro_invima',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
