# Generated by Django 6.0.4 on 2026-04-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0002_medicamento_concentracion_medicamento_laboratorio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='rol',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ubicacion_asignada',
            field=models.ForeignKey(blank=True, help_text='Ubicación física principal del usuario.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kardex.ubicacion'),
        ),
    ]
