# Generated by Django 6.0.4 on 2026-04-22 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kardex', '0003_remove_perfilusuario_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente (En Revisión)'), ('SOLICITADO', 'Solicitado (Despachado)')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='kardex.medicamento')),
                ('sede_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_realizados', to='kardex.ubicacion')),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
