# Generated by Django 6.0.4 on 2026-05-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0004_solicitudstock"),
        ("kardex", "0005_inicializar_perfiles_prueba"),
    ]

    operations = []
