# Generated by Django 6.0.4 on 2026-05-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0006_merge_20260518_1510"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamento",
            name="clasificacion_riesgo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "I - Bajo"),
                    ("IIa", "IIa - Medio"),
                    ("IIb", "IIb - Medio-Alto"),
                    ("III", "III - Alto"),
                ],
                help_text="Clasificación de riesgo INVIMA: I, IIa, IIb, III",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicamento",
            name="vida_util",
            field=models.CharField(
                blank=True,
                help_text="Ej: 5 años, 3 AÑOS, 1 año",
                max_length=50,
                null=True,
            ),
        ),
    ]
