# Generated by Django 6.0.4 on 2026-05-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0007_medicamento_clasificacion_riesgo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("MEDICAMENTO", "Medicamento"),
                    ("DISPOSITIVO", "Dispositivo Médico"),
                ],
                default="MEDICAMENTO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="medicamento",
            name="principio_activo",
            field=models.CharField(
                max_length=150, verbose_name="Nombre / Principio Activo"
            ),
        ),
    ]
