# Generated by Django 6.0.4 on 2026-05-21 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0008_medicamento_tipo_alter_medicamento_principio_activo"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudstock",
            name="grupo_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
