# Generated by Django 6.0.4 on 2026-05-25 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0009_solicitudstock_grupo_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TurnoEnfermera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_expiracion", models.DateTimeField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "enfermera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos_enfermera",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos_enfermera",
                        to="kardex.ubicacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Turno de Enfermera",
                "verbose_name_plural": "Turnos de Enfermeras",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
