# Generated by Django 6.0.4 on 2026-05-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0010_turnoenfermera"),
    ]

    operations = [
        migrations.CreateModel(
            name="CargaRIPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.CharField(
                        help_text="Nombre del archivo original", max_length=500
                    ),
                ),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                (
                    "periodo_inicio",
                    models.DateField(help_text="Fecha inicio del reporte"),
                ),
                ("periodo_fin", models.DateField(help_text="Fecha fin del reporte")),
                ("total_registros", models.PositiveIntegerField(default=0)),
                (
                    "registros_medicamentos",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Solo MEDICAMENTO + SERVICIO FARMACEUTICO + INSUMOS",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CARGADA", "Cargada"),
                            ("CONCILIADA", "Conciliada"),
                            ("ERROR", "Error"),
                        ],
                        default="CARGADA",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Carga RIPS",
                "verbose_name_plural": "Cargas RIPS",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="Conciliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_conciliacion", models.DateTimeField(auto_now_add=True)),
                ("periodo_inicio", models.DateField()),
                ("periodo_fin", models.DateField()),
                (
                    "total_salidas_kardex",
                    models.PositiveIntegerField(
                        default=0, help_text="Total de SALIDAS en el Kardex"
                    ),
                ),
                (
                    "total_medicamentos_kardex",
                    models.PositiveIntegerField(
                        default=0, help_text="Suma de cantidades de SALIDAS"
                    ),
                ),
                ("total_registros_rips", models.PositiveIntegerField(default=0)),
                ("total_cantidad_rips", models.PositiveIntegerField(default=0)),
                ("coincidencias", models.PositiveIntegerField(default=0)),
                (
                    "no_facturados",
                    models.PositiveIntegerField(
                        default=0, help_text="En Kardex pero no en RIPS"
                    ),
                ),
                (
                    "no_despachados",
                    models.PositiveIntegerField(
                        default=0, help_text="En RIPS pero no en Kardex"
                    ),
                ),
                (
                    "carga_rips",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conciliaciones",
                        to="kardex.cargarips",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conciliación",
                "verbose_name_plural": "Conciliaciones",
                "ordering": ["-fecha_conciliacion"],
            },
        ),
        migrations.CreateModel(
            name="RegistroRIPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gruposervicio", models.CharField(db_index=True, max_length=100)),
                ("cupscodigo", models.CharField(db_index=True, max_length=20)),
                ("nombreprocedimiento", models.CharField(max_length=500)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "valorunitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "valortotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "identificacion_paciente",
                    models.CharField(db_index=True, max_length=50),
                ),
                (
                    "nombre_paciente",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "identificacion_profesional",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "nombre_profesional",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "especialidad",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "fechaprocedimiento",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "numerofactura",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("sede", models.CharField(blank=True, default="", max_length=200)),
                ("admision", models.CharField(blank=True, default="", max_length=100)),
                ("modalidad", models.CharField(blank=True, default="", max_length=50)),
                (
                    "diagnostico",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "diagnosticonombre",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "carga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="kardex.cargarips",
                    ),
                ),
                (
                    "medicamento_mapeado",
                    models.ForeignKey(
                        blank=True,
                        help_text="Medicamento del Kardex con el que se mapeó automáticamente",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kardex.medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro RIPS",
                "verbose_name_plural": "Registros RIPS",
            },
        ),
        migrations.CreateModel(
            name="DetalleConciliacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("COINCIDE", "✅ Coincide"),
                            ("NO_FACTURADO", "❌ No Facturado"),
                            ("NO_DESPACHADO", "⚠️ No Despachado"),
                            ("CANTIDAD_DIF", "🔄 Cantidad Diferente"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("medicamento_nombre", models.CharField(max_length=300)),
                (
                    "paciente_identificacion",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "paciente_nombre",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("cantidad_kardex", models.PositiveIntegerField(default=0)),
                ("cantidad_rips", models.PositiveIntegerField(default=0)),
                ("fecha", models.DateTimeField()),
                ("sede", models.CharField(blank=True, default="", max_length=200)),
                (
                    "profesional",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("observacion", models.TextField(blank=True, default="")),
                (
                    "conciliacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="kardex.conciliacion",
                    ),
                ),
                (
                    "documento_salida",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kardex.documento",
                    ),
                ),
                (
                    "medicamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kardex.medicamento",
                    ),
                ),
                (
                    "registro_rips",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kardex.registrorips",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Conciliación",
                "verbose_name_plural": "Detalles de Conciliación",
            },
        ),
        migrations.CreateModel(
            name="MapeoRIPSMedicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cups_codigo",
                    models.CharField(
                        blank=True,
                        help_text="Código CUPS del RIPS (ej: 70005, 70174)",
                        max_length=20,
                    ),
                ),
                (
                    "nombre_rips",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del procedimiento en RIPS (ej: ACETAMINOFEN 500 MG TABLETA)",
                        max_length=500,
                    ),
                ),
                (
                    "gruposervicio",
                    models.CharField(
                        blank=True,
                        help_text="Grupo de servicio (MEDICAMENTO, SERVICIO FARMACEUTICO, INSUMOS)",
                        max_length=50,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "medicamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapeos_rips",
                        to="kardex.medicamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mapeo RIPS - Medicamento",
                "verbose_name_plural": "Mapeos RIPS - Medicamentos",
                "unique_together": {("medicamento", "cups_codigo", "nombre_rips")},
            },
        ),
        migrations.AddIndex(
            model_name="registrorips",
            index=models.Index(
                fields=["identificacion_paciente", "fechaprocedimiento"],
                name="kardex_regi_identif_3647cd_idx",
            ),
        ),
    ]
