# Generated by Django 6.0.4 on 2026-05-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0011_cargarips_conciliacion_registrorips_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamento",
            name="cups_codigo",
            field=models.CharField(
                blank=True,
                help_text="Código CUPS del RIPS (ej: 70005, 70174). Se usa para conciliación automática.",
                max_length=20,
                null=True,
            ),
        ),
    ]
