# Generated by Django 6.0.4 on 2026-05-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0012_medicamento_cups_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="perfilusuario",
            name="last_password_change",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora del último cambio de contraseña.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="perfilusuario",
            name="must_change_password",
            field=models.BooleanField(
                default=True,
                help_text="Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión.",
            ),
        ),
    ]
