# Generated by Django 6.0.4 on 2026-05-27 21:32

from django.db import migrations
from django.contrib.auth.hashers import make_password


ENFERMERAS = [
    ('1002862835', 'YURI PAOLA BALANTA TOBAR', '1002862835'),
    ('1007431448', 'MARIA ZOLANYI RENTERIA', '1007431448'),
    ('1059985066', 'LEDY JHOANA CARABALI', '1059985066'),
    ('1059985128', 'GINA PAOLA RAMOS', '1059985128'),
    ('1059988369', 'LAURA DANIELA PALACIOS', '1059988369'),
    ('1060418777', 'INGRID VANESA VASQUEZ  MULATO', '1060418777'),
    ('1062301333', 'KEYLA YULIETH MINA PAZ', '1062301333'),
    ('1105363372', 'KATERINE DANIELA GARCES', '1105363372'),
    ('1110365602', 'NATALIA PEREA NAVARRETE', '1110365602'),
    ('1112038168', 'MIGUEL ALEJANDRO DIAZ LOBOA', '1112038168'),
    ('1130948830', 'YESI KATERINE MURILLO', '1130948830'),
    ('1133364030', 'KAROL OREJUELA', '1133364030'),
    ('1149437727', 'ERICKA VIVIANA LOBOA FORY', '1149437727'),
    ('25617701', 'YRMA DALIA VALENCIA', '25617701'),
    ('25618822', 'MARIA ZOLANDY LARRAHONDO', '25618822'),
    ('29508930', 'HELENA  QUEZADA GUTIERREZ', '29508930'),
    ('34371149', 'MARIA DENIS CANTOÑI LUCUMI', '34371149'),
    ('34374953', 'LUZ JHOHANA ROMERO', '34374953'),
    ('34515086', 'DANELLY ALEGRIA COSME', '34515086'),
    ('35893469', 'DARYLENIS MOSQUERA LONDOÑO', '35893469'),
]


def seed_enfermeras(apps, schema_editor):
    """Crea las 20 auxiliares de enfermería con clave temporal = documento completo."""
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    PerfilUsuario = apps.get_model('kardex', 'PerfilUsuario')
    Ubicacion = apps.get_model('kardex', 'Ubicacion')

    grupo_enfermera, _ = Group.objects.get_or_create(name='ENFERMERA')

    # Tomar la primera sede disponible (FarmaciaSede1 o la que exista)
    sede = Ubicacion.objects.order_by('id').first()

    for username, first_name, document in ENFERMERAS:
        user, created = User.objects.get_or_create(
            username=username,
            defaults={
                'first_name': first_name,
                'last_name': '',
                'email': '',
                'password': make_password(document),  # Clave temporal = documento
            }
        )
        if created:
            PerfilUsuario.objects.create(
                usuario=user,
                ubicacion_asignada=sede,
                numero_identificacion=document,
                must_change_password=True,
            )
            user.groups.add(grupo_enfermera)


def reverse_seed(apps, schema_editor):
    """Elimina las enfermeras creadas por esta migración."""
    User = apps.get_model('auth', 'User')
    PerfilUsuario = apps.get_model('kardex', 'PerfilUsuario')
    usernames = [u[0] for u in ENFERMERAS]
    PerfilUsuario.objects.filter(usuario__username__in=usernames).delete()
    User.objects.filter(username__in=usernames).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0013_perfilusuario_last_password_change_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_enfermeras, reverse_seed),
    ]
