# Generated by Django 6.0.4 on 2026-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0023_remove_unique_codigo"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicamento",
            name="unidad_medida",
            field=models.CharField(
                blank=True,
                help_text="Ej: Tableta, Ampolleta, mL, Gramo",
                max_length=50,
                null=True,
            ),
        ),
    ]
