# Generated by Django 6.0.4 on 2026-06-18 15:58

"""
Migracion 0025: Agrega unique_together a Medicamento.

ANTES de aplicar el constraint, normaliza concentracion='' a NULL
y consolida los registros duplicados existentes.

Esto evita que la migracion falle por violacion de unicidad.
"""

from django.db import migrations, transaction
from django.db.models import Count


def normalizar_y_consolidar(apps, schema_editor):
    """
    1. Normaliza concentracion='' a NULL
    2. Consolida medicamentos duplicados: mismo PA + FF + conc
       migrando todo el stock al registro canonico y eliminando duplicados.
    """
    Medicamento = apps.get_model('kardex', 'Medicamento')
    InventarioStock = apps.get_model('kardex', 'InventarioStock')
    SolicitudStock = apps.get_model('kardex', 'SolicitudStock')
    DocumentoDetalle = apps.get_model('kardex', 'DocumentoDetalle')
    DetalleConciliacion = apps.get_model('kardex', 'DetalleConciliacion')
    MapeoRIPSMedicamento = apps.get_model('kardex', 'MapeoRIPSMedicamento')

    # Paso 1: Normalizar '' a NULL
    updated = Medicamento.objects.filter(concentracion='').update(concentracion=None)
    if updated:
        print(f'  Normalizados {updated} registros con concentracion="" a NULL')

    # Paso 2: Consolidar duplicados
    all_meds = Medicamento.objects.all().order_by(
        'principio_activo', 'forma_farmaceutica', 'concentracion', 'id'
    )

    groups = {}
    for m in all_meds:
        key = (m.principio_activo, m.forma_farmaceutica, m.concentracion)
        groups.setdefault(key, []).append(m)

    total_deleted = 0

    for key, members in groups.items():
        if len(members) <= 1:
            continue

        pa, ff, conc = key
        members_sorted = sorted(
            members,
            key=lambda m: InventarioStock.objects.filter(medicamento=m).count(),
            reverse=True,
        )
        canonical = members_sorted[0]
        to_delete = members_sorted[1:]

        print(f'  Consolidando "{pa[:60]}..." ({ff}) — {len(to_delete)} duplicados')

        for dup in to_delete:
            with transaction.atomic():
                # Migrar InventarioStock
                for stock in InventarioStock.objects.filter(medicamento=dup):
                    existing = InventarioStock.objects.filter(
                        ubicacion=stock.ubicacion,
                        medicamento=canonical,
                        lote=stock.lote,
                    ).first()
                    if existing:
                        existing.cantidad_actual += stock.cantidad_actual
                        existing.save()
                        stock.delete()
                    else:
                        InventarioStock.objects.filter(id=stock.id).update(
                            medicamento=canonical
                        )

                # Migrar SolicitudStock
                SolicitudStock.objects.filter(medicamento=dup).update(
                    medicamento=canonical
                )
                # Migrar DocumentoDetalle
                DocumentoDetalle.objects.filter(medicamento=dup).update(
                    medicamento=canonical
                )
                # Migrar DetalleConciliacion
                DetalleConciliacion.objects.filter(medicamento=dup).update(
                    medicamento=canonical
                )
                # Migrar MapeoRIPS
                MapeoRIPSMedicamento.objects.filter(medicamento=dup).update(
                    medicamento=canonical
                )

                dup.delete()
                total_deleted += 1

    if total_deleted:
        print(f'  Eliminados {total_deleted} registros duplicados de Medicamento')


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0024_add_unidad_medida"),
    ]

    operations = [
        migrations.RunPython(
            normalizar_y_consolidar,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name="medicamento",
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
            },
        ),
        migrations.AlterUniqueTogether(
            name="medicamento",
            unique_together={
                ("principio_activo", "forma_farmaceutica", "concentracion")
            },
        ),
    ]
