# Generated by Django 6.0.4 on 2026-06-18 16:30

"""
Migracion 0026: Agrega unique_together a Medicamento.

SEPARADA de la migracion 0025 para evitar el error de PostgreSQL:
"cannot ALTER TABLE because it has pending trigger events".

La migracion 0025 limpio los duplicados, ahora se puede aplicar
el constraint de unicidad sin problemas.
"""

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kardex", "0025_alter_medicamento_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="medicamento",
            unique_together={
                ("principio_activo", "forma_farmaceutica", "concentracion")
            },
        ),
    ]
